name: sleep-states
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipykernel
  - keras
  - numpy
  - pandas
  - matplotlib
  - dask
  - polars
  - scikit-learn
  - h5py
  - pillow
  - seaborn
  - pyarrow
  - fastparquet
  - scipy
  - tqdm
  - dask
  - pip
  - pip:
      - tensorflow
      - watermark
